"""added user_metadata table

Revision ID: 2c5f57795405
Revises: 6e66913dd4a8
Create Date: 2025-08-01 16:52:05.875067

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c5f57795405"
down_revision: Union[str, None] = "6e66913dd4a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_metadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("userAddress", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("birthMonth", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("birthYear", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("isItRelated", sa.Boolean(), nullable=False),
        sa.Column("submittedAt", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["userAddress"],
            ["users.address"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_metadata")
    # ### end Alembic commands ###
