"""empty message

Revision ID: c00c9fa926f6
Revises: df4d103d856e
Create Date: 2025-08-10 23:12:29.018333

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "c00c9fa926f6"
down_revision: Union[str, None] = "df4d103d856e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_statistics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("userAddress", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("audioLength", sa.Float(), nullable=False),
        sa.Column("time", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_statistics")
    # ### end Alembic commands ###
