"""empty message

Revision ID: c07cee8cf2f1
Revises: c00c9fa926f6
Create Date: 2025-08-12 04:16:39.017617

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "c07cee8cf2f1"
down_revision: Union[str, None] = "c00c9fa926f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_metadata", sa.Column("contributedSeconds", sa.Float(), default=0)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_metadata", "contributedSeconds")
    # ### end Alembic commands ###
