"""empty message

Revision ID: c56ee0166624
Revises: c07cee8cf2f1
Create Date: 2025-08-12 04:38:51.900670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c56ee0166624'
down_revision: Union[str, None] = 'c07cee8cf2f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_statistics')
    op.alter_column('user_metadata', 'contributedSeconds',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_metadata', 'contributedSeconds',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_table('user_statistics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userAddress', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('audioLength', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_statistics_pkey'))
    )
    # ### end Alembic commands ###
