"""empty message

Revision ID: df4d103d856e
Revises: 
Create Date: 2025-08-10 01:53:44.965356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'df4d103d856e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fingerprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fprint', sa.LargeBinary(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chainId', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('connectedAt', sa.DateTime(), nullable=False),
    sa.Column('lastActivity', sa.DateTime(), nullable=False),
    sa.Column('violations', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('address')
    )
    op.create_index(op.f('ix_users_address'), 'users', ['address'], unique=True)
    op.create_table('user_metadata',
    sa.Column('userAddress', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('countryCode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('birthMonth', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('birthYear', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('isItRelated', sa.Boolean(), nullable=False),
    sa.Column('submittedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userAddress'], ['users.address'], ),
    sa.PrimaryKeyConstraint('userAddress')
    )
    op.create_table('user_statistics',
    sa.Column('userAddress', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('audioLength', sa.Float(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userAddress'], ['users.address'], ),
    sa.PrimaryKeyConstraint('userAddress')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_statistics')
    op.drop_table('user_metadata')
    op.drop_index(op.f('ix_users_address'), table_name='users')
    op.drop_table('users')
    op.drop_table('fingerprints')
    # ### end Alembic commands ###
